sudo: false
dist: xenial
language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly-2019-03-15
      env:
        - CARGO_INCREMENTAL=0
        - RUSTFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'

install:
- rustup component add rustfmt clippy
- if [[ "$TRAVIS_RUST_VERSION" = nightly* ]]; then cargo install -f grcov; fi

script:
- cargo build --all-features --verbose
- cargo test --all-features --verbose
- if [[ "$TRAVIS_RUST_VERSION" = nightly* ]]; then ./coverage.sh; fi
- cargo clippy -- -Dwarnings
- cargo clippy --tests -- -Dwarnings
- cargo fmt --all -- --check
- cargo doc --no-deps

after_success:
- if [[ "$TRAVIS_RUST_VERSION" = nightly* ]]; then bash <(curl -s https://codecov.io/bash) -f lcov.info; fi
